version: "3.9"
services:
  
  app:
    container_name: simple_go_service
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    networks:
      - net

  postgres:
    container_name: pgdb
    image: postgres:latest 
    #command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_DB: "pgdb"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./PostgreSQL/pgdata:/var/lib/postgresql/data/pgdata
      #- ./PostgreSQL/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    expose:
      - 5432
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - net

networks:
   net:
       driver: bridge