version: "3.9"
services:
  
  app:
    container_name: simple_go_service
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    links:
      - "postgres"
      - "elasticsearch"

  postgres:
    container_name: pgdb
    image: postgres:latest 
    environment:
      POSTGRES_DB: "pgdb"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      #- ./PostgreSQL/pgdata:/var/lib/postgresql/data/pgdata
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    expose:
      - 5432
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - discovery.type=single-node
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    expose:
      - 5601
    links:
      - "elasticsearch"